name: Build

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.4.0

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.21.1'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install Linux Build Dependencies
        run: sudo apt-get update && sudo apt-get install -y icnsutils graphicsmagick xz-utils libx11-dev libxkbfile-dev gnome-keyring libsecret-1-dev libfontconfig-dev rpm

      - name: Run postinstall
        run: pnpm tsx scripts/postinstall.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_user_agent: 'pnpm'

      - name: Build Linux
        run: pnpm run build:linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marktext-linux
          retention-days: 30
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
          if-no-files-found: error

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.4.0

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.21.1'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run postinstall
        run: pnpm tsx scripts/postinstall.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_user_agent: 'pnpm'

      - name: Build Windows
        run: pnpm run build:win

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marktext-windows
          retention-days: 30
          path: |
            dist/*.exe
            dist/*.zip
          if-no-files-found: error
